

export const authConstants = {
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGOUT_REQUEST: 'LOGOUT_REQUEST',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAILURE: 'LOGOUT_FAILURE',


    SIGNUP_REQUEST: "SIGNUP_REQUEST",
    SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
    SIGNUP_FAILURE: "SIGNUP_FAILURE",

    SET_TOKEN: "SET_TOKEN",
}

export const postConstants = {
    POST_REQUEST: 'POST_REQUEST',
    POST_SUCCESS: 'POST_SUCCESS',
    POST_FAILURE: 'POST_FAILURE',
    POST_CREATE_ERROR: 'POST_CREATE_ERROR',

    SET_MESSAGE: 'SET_MESSAGE',


    GET_POST_REQUEST: 'GET_POST_REQUEST',
    GET_POST_SUCCESS: 'GET_POST_SUCCESS',
    GET_POST_FAILURE: 'GET_POST_FAILURE',


    GET_POST_DETAIL_REQUEST: 'GET_POST_DETAIL_REQUEST',
    GET_POST_DETAIL_SUCCESS: 'GET_POST_DETAIL_SUCCESS',
    GET_POST_DETAIL_FAILURE: 'GET_POST_DETAIL_FAILURE',


    POST_COMMENT_REQUEST: 'POST_COMMENT_REQUEST',
    POST_COMMENT_SUCCESS: 'POST_COMMENT_SUCCESS',
    POST_COMMENT_FAILURE: 'POST_COMMENT_FAILURE',

    POST_DELETE_REQUEST: 'POST_DELETE_REQUEST',
    POST_DELETE_SUCCESS: 'POST_DELETE_SUCCESS',
    POST_DELETE_FAILURE: 'POST_DELETE_FAILURE',


    POST_EDIT_REQUEST: 'POST_EDIT_REQUEST',
    POST_EDIT_SUCCESS: 'POST_EDIT_SUCCESS',
    POST_EDIT_FAILURE: 'POST_EDIT_FAILURE',


    POST_EDITDATA_REQUEST: 'POST_EDITDATA_REQUEST',
    POST_EDITDATA_SUCCESS: 'POST_EDITDATA_SUCCESS',
    POST_EDITDATA_FAILURE: 'POST_EDITDATA_FAILURE',
}


export const dashboardConstants = {
    GET_DASHBOARD_REQUEST: 'GET_DASHBOARD_REQUEST',
    GET_DASHBOARD_SUCCESS: 'GET_DASHBOARD_SUCCESS',
    GET_DASHBOARD_FAILURE: 'GET_DASHBOARD_FAILURE'

}